#include <fstream>
#include <generator.hpp>
#include <iostream>
#include <model.hpp>
#include <stream.hpp>

namespace Reflector
{
	namespace fs = std::filesystem;

	static bool is_object_empty(const Object* object)
	{
		if (object == nullptr)
			return true;

		switch (object->kind())
		{
			case ObjectKind::Enum:
			case ObjectKind::Struct:
			case ObjectKind::Class:
			case ObjectKind::Function:
			case ObjectKind::Property: return false;

			case ObjectKind::Object: return true;

			case ObjectKind::Scope:
			case ObjectKind::Namespace:
			case ObjectKind::Module:
			{
				auto scope = dynamic_cast<const Scope*>(object);

				for (Object* child : scope->objects)
				{
					if (!is_object_empty(child))
					{
						return false;
					}
				}

				return true;
			}

			default: return true;
		}
	}

	static void write_generated_header(CodeWriter* writer)
	{
		writer->write("// ============================================================================\n"
		              "// Trinex Engine - Auto-generated File\n"
		              "// Generated by Trinex Reflector\n"
		              "//\n"
		              "// DO NOT EDIT! All changes will be overwritten during code generation.\n"
		              "// ============================================================================\n\n");
	}

	static bool generate_header(CodeWriter* writer, const Module* module)
	{
		write_generated_header(writer);
		return true;
	}

	static bool generate_source(CodeWriter* writer, const Module* module)
	{
		write_generated_header(writer);
		return true;
	}

	static bool save_generated_file(const fs::path& path, CodeWriter* writer)
	{
		const fs::path parent = path.parent_path();

		if (!parent.empty())
		{
			std::error_code ec;
			fs::create_directories(parent, ec);

			if (ec)
			{
				std::cerr << "Error: Failed to create directory '" << parent << "': " << ec.message() << '\n';
				return false;
			}
		}

		std::ofstream file(path, std::ios::binary | std::ios::trunc);

		if (!file)
		{
			std::cerr << "Error: Failed to open generated file: " << path << '\n';
			return false;
		}

		auto content = writer->text();
		file.write(content.data(), content.size());
		file.close();

		if (!file)
		{
			std::cerr << "Error: Failed to write generated file: " << path << '\n';
			return false;
		}

		return true;
	}

	bool generate_header(fs::path path, const Module* module)
	{
		if (is_object_empty(module))
			return true;

		CodeWriter header;

		if (!generate_header(&header, module))
		{
			return false;
		}

		return save_generated_file(path, &header);
	}

	bool generate_source(fs::path path, const Module* module)
	{
		if (is_object_empty(module))
			return true;

		CodeWriter source;

		if (!generate_header(&source, module))
		{
			return false;
		}

		return save_generated_file(path, &source);
	}
}// namespace Reflector
