#include <Core/keyboard.hpp>
#include <Core/predef.hpp>
#include <SDL_keyboard.h>
#include <SDL_mouse.h>


namespace Engine
{
    static Map<Key, int> keyboard = {{KEY_UNKNOWN, SDL_SCANCODE_UNKNOWN},
                                                    {KEY_SPACE, SDL_SCANCODE_SPACE},
                                                    {KEY_APOSTROPHE, SDL_SCANCODE_APOSTROPHE},
                                                    {KEY_COMMA, SDL_SCANCODE_COMMA},
                                                    {KEY_MINUS, SDL_SCANCODE_MINUS},
                                                    {KEY_PERIOD, SDL_SCANCODE_PERIOD},
                                                    {KEY_SLASH, SDL_SCANCODE_SLASH},
                                                    {KEY_0, SDL_SCANCODE_0},
                                                    {KEY_1, SDL_SCANCODE_1},
                                                    {KEY_2, SDL_SCANCODE_2},
                                                    {KEY_3, SDL_SCANCODE_3},
                                                    {KEY_4, SDL_SCANCODE_4},
                                                    {KEY_5, SDL_SCANCODE_5},
                                                    {KEY_6, SDL_SCANCODE_6},
                                                    {KEY_7, SDL_SCANCODE_7},
                                                    {KEY_8, SDL_SCANCODE_8},
                                                    {KEY_9, SDL_SCANCODE_9},
                                                    {KEY_SEMICOLON, SDL_SCANCODE_SEMICOLON},
                                                    {KEY_EQUAL, SDL_SCANCODE_EQUALS},
                                                    {KEY_A, SDL_SCANCODE_A},
                                                    {KEY_B, SDL_SCANCODE_B},
                                                    {KEY_C, SDL_SCANCODE_C},
                                                    {KEY_D, SDL_SCANCODE_D},
                                                    {KEY_E, SDL_SCANCODE_E},
                                                    {KEY_F, SDL_SCANCODE_F},
                                                    {KEY_G, SDL_SCANCODE_G},
                                                    {KEY_H, SDL_SCANCODE_H},
                                                    {KEY_I, SDL_SCANCODE_I},
                                                    {KEY_J, SDL_SCANCODE_J},
                                                    {KEY_K, SDL_SCANCODE_K},
                                                    {KEY_L, SDL_SCANCODE_L},
                                                    {KEY_M, SDL_SCANCODE_M},
                                                    {KEY_N, SDL_SCANCODE_N},
                                                    {KEY_O, SDL_SCANCODE_O},
                                                    {KEY_P, SDL_SCANCODE_P},
                                                    {KEY_Q, SDL_SCANCODE_Q},
                                                    {KEY_R, SDL_SCANCODE_R},
                                                    {KEY_S, SDL_SCANCODE_S},
                                                    {KEY_T, SDL_SCANCODE_T},
                                                    {KEY_U, SDL_SCANCODE_U},
                                                    {KEY_V, SDL_SCANCODE_V},
                                                    {KEY_W, SDL_SCANCODE_W},
                                                    {KEY_X, SDL_SCANCODE_X},
                                                    {KEY_Y, SDL_SCANCODE_Y},
                                                    {KEY_Z, SDL_SCANCODE_Z},
                                                    {KEY_LEFT_BRACKET, SDL_SCANCODE_LEFTBRACKET},
                                                    {KEY_BACKSLASH, SDL_SCANCODE_BACKSLASH},
                                                    {KEY_RIGHT_BRACKET, SDL_SCANCODE_RIGHTBRACKET},
                                                    {KEY_GRAVE_ACCENT, SDL_SCANCODE_GRAVE},
                                                    {KEY_WWW, SDL_SCANCODE_WWW},
                                                    {KEY_ESCAPE, SDL_SCANCODE_ESCAPE},
                                                    {KEY_ENTER, SDL_SCANCODE_RETURN},
                                                    {KEY_TAB, SDL_SCANCODE_TAB},
                                                    {KEY_BACKSPACE, SDL_SCANCODE_BACKSPACE},
                                                    {KEY_INSERT, SDL_SCANCODE_INSERT},
                                                    {KEY_DELETE, SDL_SCANCODE_DELETE},
                                                    {KEY_RIGHT, SDL_SCANCODE_RIGHT},
                                                    {KEY_LEFT, SDL_SCANCODE_LEFT},
                                                    {KEY_DOWN, SDL_SCANCODE_DOWN},
                                                    {KEY_UP, SDL_SCANCODE_UP},
                                                    {KEY_PAGE_UP, SDL_SCANCODE_PAGEUP},
                                                    {KEY_PAGE_DOWN, SDL_SCANCODE_PAGEDOWN},
                                                    {KEY_HOME, SDL_SCANCODE_HOME},
                                                    {KEY_END, SDL_SCANCODE_END},
                                                    {KEY_CAPS_LOCK, SDL_SCANCODE_CAPSLOCK},
                                                    {KEY_SCROLL_LOCK, SDL_SCANCODE_SCROLLLOCK},
                                                    {KEY_NUM_LOCK, SDL_SCANCODE_NUMLOCKCLEAR},
                                                    {KEY_PRINT_SCREEN, SDL_SCANCODE_PRINTSCREEN},
                                                    {KEY_PAUSE, SDL_SCANCODE_PAUSE},
                                                    {KEY_F1, SDL_SCANCODE_F1},
                                                    {KEY_F2, SDL_SCANCODE_F2},
                                                    {KEY_F3, SDL_SCANCODE_F3},
                                                    {KEY_F4, SDL_SCANCODE_F4},
                                                    {KEY_F5, SDL_SCANCODE_F5},
                                                    {KEY_F6, SDL_SCANCODE_F6},
                                                    {KEY_F7, SDL_SCANCODE_F7},
                                                    {KEY_F8, SDL_SCANCODE_F8},
                                                    {KEY_F9, SDL_SCANCODE_F9},
                                                    {KEY_F10, SDL_SCANCODE_F10},
                                                    {KEY_F11, SDL_SCANCODE_F11},
                                                    {KEY_F12, SDL_SCANCODE_F12},
                                                    {KEY_F13, SDL_SCANCODE_F13},
                                                    {KEY_F14, SDL_SCANCODE_F14},
                                                    {KEY_F15, SDL_SCANCODE_F15},
                                                    {KEY_F16, SDL_SCANCODE_F16},
                                                    {KEY_F17, SDL_SCANCODE_F17},
                                                    {KEY_F18, SDL_SCANCODE_F18},
                                                    {KEY_F19, SDL_SCANCODE_F19},
                                                    {KEY_F20, SDL_SCANCODE_F20},
                                                    {KEY_F21, SDL_SCANCODE_F21},
                                                    {KEY_F22, SDL_SCANCODE_F22},
                                                    {KEY_F23, SDL_SCANCODE_F23},
                                                    {KEY_F24, SDL_SCANCODE_F24},
                                                    {KEY_KP_0, SDL_SCANCODE_KP_0},
                                                    {KEY_KP_1, SDL_SCANCODE_KP_1},
                                                    {KEY_KP_2, SDL_SCANCODE_KP_2},
                                                    {KEY_KP_3, SDL_SCANCODE_KP_3},
                                                    {KEY_KP_4, SDL_SCANCODE_KP_4},
                                                    {KEY_KP_5, SDL_SCANCODE_KP_5},
                                                    {KEY_KP_6, SDL_SCANCODE_KP_6},
                                                    {KEY_KP_7, SDL_SCANCODE_KP_7},
                                                    {KEY_KP_8, SDL_SCANCODE_KP_8},
                                                    {KEY_KP_9, SDL_SCANCODE_KP_9},
                                                    {KEY_KP_DECIMAL, SDL_SCANCODE_KP_DECIMAL},
                                                    {KEY_KP_DIVIDE, SDL_SCANCODE_KP_DIVIDE},
                                                    {KEY_KP_MULTIPLY, SDL_SCANCODE_KP_MULTIPLY},
                                                    {KEY_KP_SUBTRACT, SDL_SCANCODE_KP_MINUS},
                                                    {KEY_KP_ADD, SDL_SCANCODE_KP_PLUS},
                                                    {KEY_KP_ENTER, SDL_SCANCODE_KP_ENTER},
                                                    {KEY_KP_EQUAL, SDL_SCANCODE_KP_EQUALS},
                                                    {KEY_LEFT_SHIFT, SDL_SCANCODE_LSHIFT},
                                                    {KEY_LEFT_CONTROL, SDL_SCANCODE_LCTRL},
                                                    {KEY_LEFT_ALT, SDL_SCANCODE_LALT},
                                                    {KEY_LEFT_SUPER, SDL_SCANCODE_LGUI},
                                                    {KEY_RIGHT_SHIFT, SDL_SCANCODE_RSHIFT},
                                                    {KEY_RIGHT_CONTROL, SDL_SCANCODE_RCTRL},
                                                    {KEY_RIGHT_ALT, SDL_SCANCODE_RALT},
                                                    {KEY_RIGHT_SUPER, SDL_SCANCODE_RGUI},
                                                    {KEY_MENU, SDL_SCANCODE_MENU},
                                                    {MOUSE_BUTTON_LEFT, SDL_BUTTON_LEFT},
                                                    {MOUSE_BUTTON_RIGHT, SDL_BUTTON_RIGHT},
                                                    {MOUSE_BUTTON_MIDDLE, SDL_BUTTON_MIDDLE}};

    static Map<int, Key> reversed_keyboard;

    static struct ReverseKeyboardGenerator {
        ReverseKeyboardGenerator()
        {
            for (auto& keyboard_pair : keyboard) reversed_keyboard[keyboard_pair.second] = keyboard_pair.first;
        }
    } rkb_gen;




    static Map<Key, std::string> key_names = {{KEY_UNKNOWN, "UNKNOWN"},
                                                             {KEY_SPACE, "SPACE"},
                                                             {KEY_APOSTROPHE, "APOSTROPHE"},
                                                             {KEY_COMMA, "COMMA"},
                                                             {KEY_MINUS, "MINUS"},
                                                             {KEY_PERIOD, "PERIOD"},
                                                             {KEY_SLASH, "SLASH"},
                                                             {KEY_0, "0"},
                                                             {KEY_1, "1"},
                                                             {KEY_2, "2"},
                                                             {KEY_3, "3"},
                                                             {KEY_4, "4"},
                                                             {KEY_5, "5"},
                                                             {KEY_6, "6"},
                                                             {KEY_7, "7"},
                                                             {KEY_8, "8"},
                                                             {KEY_9, "9"},
                                                             {KEY_SEMICOLON, "SEMICOLON"},
                                                             {KEY_EQUAL, "EQUAL"},
                                                             {KEY_A, "A"},
                                                             {KEY_B, "B"},
                                                             {KEY_C, "C"},
                                                             {KEY_D, "D"},
                                                             {KEY_E, "E"},
                                                             {KEY_F, "F"},
                                                             {KEY_G, "G"},
                                                             {KEY_H, "H"},
                                                             {KEY_I, "I"},
                                                             {KEY_J, "J"},
                                                             {KEY_K, "K"},
                                                             {KEY_L, "L"},
                                                             {KEY_M, "M"},
                                                             {KEY_N, "N"},
                                                             {KEY_O, "O"},
                                                             {KEY_P, "P"},
                                                             {KEY_Q, "Q"},
                                                             {KEY_R, "R"},
                                                             {KEY_S, "S"},
                                                             {KEY_T, "T"},
                                                             {KEY_U, "U"},
                                                             {KEY_V, "V"},
                                                             {KEY_W, "W"},
                                                             {KEY_X, "X"},
                                                             {KEY_Y, "Y"},
                                                             {KEY_Z, "Z"},
                                                             {KEY_LEFT_BRACKET, "LEFT_BRACKET"},
                                                             {KEY_BACKSLASH, "BACKSLASH"},
                                                             {KEY_RIGHT_BRACKET, "RIGHT_BRACKET"},
                                                             {KEY_GRAVE_ACCENT, "GRAVE_ACCENT"},
                                                             {KEY_WWW, "WWW"},
                                                             {KEY_ESCAPE, "ESCAPE"},
                                                             {KEY_ENTER, "ENTER"},
                                                             {KEY_TAB, "TAB"},
                                                             {KEY_BACKSPACE, "BACKSPACE"},
                                                             {KEY_INSERT, "INSERT"},
                                                             {KEY_DELETE, "DELETE"},
                                                             {KEY_RIGHT, "RIGHT"},
                                                             {KEY_LEFT, "LEFT"},
                                                             {KEY_DOWN, "DOWN"},
                                                             {KEY_UP, "UP"},
                                                             {KEY_PAGE_UP, "PAGE_UP"},
                                                             {KEY_PAGE_DOWN, "PAGE_DOWN"},
                                                             {KEY_HOME, "HOME"},
                                                             {KEY_END, "END"},
                                                             {KEY_CAPS_LOCK, "CAPS_LOCK"},
                                                             {KEY_SCROLL_LOCK, "SCROLL_LOCK"},
                                                             {KEY_NUM_LOCK, "NUM_LOCK"},
                                                             {KEY_PRINT_SCREEN, "PRINT_SCREEN"},
                                                             {KEY_PAUSE, "PAUSE"},
                                                             {KEY_F1, "F1"},
                                                             {KEY_F2, "F2"},
                                                             {KEY_F3, "F3"},
                                                             {KEY_F4, "F4"},
                                                             {KEY_F5, "F5"},
                                                             {KEY_F6, "F6"},
                                                             {KEY_F7, "F7"},
                                                             {KEY_F8, "F8"},
                                                             {KEY_F9, "F9"},
                                                             {KEY_F10, "F10"},
                                                             {KEY_F11, "F11"},
                                                             {KEY_F12, "F12"},
                                                             {KEY_F13, "F13"},
                                                             {KEY_F14, "F14"},
                                                             {KEY_F15, "F15"},
                                                             {KEY_F16, "F16"},
                                                             {KEY_F17, "F17"},
                                                             {KEY_F18, "F18"},
                                                             {KEY_F19, "F19"},
                                                             {KEY_F20, "F20"},
                                                             {KEY_F21, "F21"},
                                                             {KEY_F22, "F22"},
                                                             {KEY_F23, "F23"},
                                                             {KEY_F24, "F24"},
                                                             {KEY_KP_0, "KP_0"},
                                                             {KEY_KP_1, "KP_1"},
                                                             {KEY_KP_2, "KP_2"},
                                                             {KEY_KP_3, "KP_3"},
                                                             {KEY_KP_4, "KP_4"},
                                                             {KEY_KP_5, "KP_5"},
                                                             {KEY_KP_6, "KP_6"},
                                                             {KEY_KP_7, "KP_7"},
                                                             {KEY_KP_8, "KP_8"},
                                                             {KEY_KP_9, "KP_9"},
                                                             {KEY_KP_DECIMAL, "KP_DECIMAL"},
                                                             {KEY_KP_DIVIDE, "KP_DIVIDE"},
                                                             {KEY_KP_MULTIPLY, "KP_MULTIPLY"},
                                                             {KEY_KP_SUBTRACT, "KP_SUBTRACT"},
                                                             {KEY_KP_ADD, "KP_ADD"},
                                                             {KEY_KP_ENTER, "KP_ENTER"},
                                                             {KEY_KP_EQUAL, "KP_EQUAL"},
                                                             {KEY_LEFT_SHIFT, "LEFT_SHIFT"},
                                                             {KEY_LEFT_CONTROL, "LEFT_CONTROL"},
                                                             {KEY_LEFT_ALT, "LEFT_ALT"},
                                                             {KEY_LEFT_SUPER, "LEFT_SUPER"},
                                                             {KEY_RIGHT_SHIFT, "RIGHT_SHIFT"},
                                                             {KEY_RIGHT_CONTROL, "RIGHT_CONTROL"},
                                                             {KEY_RIGHT_ALT, "RIGHT_ALT"},
                                                             {KEY_RIGHT_SUPER, "RIGHT_SUPER"},
                                                             {KEY_MENU, "MENU"},
                                                             {MOUSE_BUTTON_LEFT, "MOUSE_BUTTON_LEFT"},
                                                             {MOUSE_BUTTON_RIGHT, "MOUSE_BUTTON_RIGHT"},
                                                             {MOUSE_BUTTON_MIDDLE, "MOUSE_BUTTON_MIDDLE"}};


    ENGINE_EXPORT int to_SDL_scancode(const Key& key)
    {
        return keyboard.at(key);
    }

    ENGINE_EXPORT wchar_t to_character(const Key& key)
    {
        return SDL_GetKeyFromScancode((SDL_Scancode) to_SDL_scancode(key));
    }

    ENGINE_EXPORT Key to_key(int value)
    {
        return reversed_keyboard.at(value);
    }

    ENGINE_EXPORT const std::string& get_key_name(const Key& key)
    {
        return key_names.at(key);
    }

    ENGINE_EXPORT std::ostream& operator<<(std::ostream& stream, const KeyStatus& status)
    {
        static Map<KeyStatus, const char*> names = {{KeyStatus::JUST_RELEASED, "JUST_RELEASED"},
                                                                   {KeyStatus::RELEASED, "RELEASED"},
                                                                   {KeyStatus::JUST_PRESSED, "JUST_PRESSED"},
                                                                   {KeyStatus::PRESSED, "PRESSED"},
                                                                   {KeyStatus::REPEAT, "REPEAT"}};
        return stream << names.at(status);
    }

    ENGINE_EXPORT unsigned int key_count()
    {
        return 130;
    }
}// namespace Engine
