#include <Core/keyboard.hpp>
#include <SDL_keyboard.h>
#include <SDL_mouse.h>


namespace Engine
{
    static Map<Key, int> keyboard = {{Key::Unknown, SDL_SCANCODE_UNKNOWN},
                                     {Key::Space, SDL_SCANCODE_SPACE},
                                     {Key::Apostrophe, SDL_SCANCODE_APOSTROPHE},
                                     {Key::Comma, SDL_SCANCODE_COMMA},
                                     {Key::Minus, SDL_SCANCODE_MINUS},
                                     {Key::Period, SDL_SCANCODE_PERIOD},
                                     {Key::Slash, SDL_SCANCODE_SLASH},
                                     {Key::Num0, SDL_SCANCODE_0},
                                     {Key::Num1, SDL_SCANCODE_1},
                                     {Key::Num2, SDL_SCANCODE_2},
                                     {Key::Num3, SDL_SCANCODE_3},
                                     {Key::Num4, SDL_SCANCODE_4},
                                     {Key::Num5, SDL_SCANCODE_5},
                                     {Key::Num6, SDL_SCANCODE_6},
                                     {Key::Num7, SDL_SCANCODE_7},
                                     {Key::Num8, SDL_SCANCODE_8},
                                     {Key::Num9, SDL_SCANCODE_9},
                                     {Key::Semicolon, SDL_SCANCODE_SEMICOLON},
                                     {Key::Equal, SDL_SCANCODE_EQUALS},
                                     {Key::A, SDL_SCANCODE_A},
                                     {Key::B, SDL_SCANCODE_B},
                                     {Key::C, SDL_SCANCODE_C},
                                     {Key::D, SDL_SCANCODE_D},
                                     {Key::E, SDL_SCANCODE_E},
                                     {Key::F, SDL_SCANCODE_F},
                                     {Key::G, SDL_SCANCODE_G},
                                     {Key::H, SDL_SCANCODE_H},
                                     {Key::I, SDL_SCANCODE_I},
                                     {Key::J, SDL_SCANCODE_J},
                                     {Key::K, SDL_SCANCODE_K},
                                     {Key::L, SDL_SCANCODE_L},
                                     {Key::M, SDL_SCANCODE_M},
                                     {Key::N, SDL_SCANCODE_N},
                                     {Key::O, SDL_SCANCODE_O},
                                     {Key::P, SDL_SCANCODE_P},
                                     {Key::Q, SDL_SCANCODE_Q},
                                     {Key::R, SDL_SCANCODE_R},
                                     {Key::S, SDL_SCANCODE_S},
                                     {Key::T, SDL_SCANCODE_T},
                                     {Key::U, SDL_SCANCODE_U},
                                     {Key::V, SDL_SCANCODE_V},
                                     {Key::W, SDL_SCANCODE_W},
                                     {Key::X, SDL_SCANCODE_X},
                                     {Key::Y, SDL_SCANCODE_Y},
                                     {Key::Z, SDL_SCANCODE_Z},
                                     {Key::LeftBracket, SDL_SCANCODE_LEFTBRACKET},
                                     {Key::Backslash, SDL_SCANCODE_BACKSLASH},
                                     {Key::RightBracket, SDL_SCANCODE_RIGHTBRACKET},
                                     {Key::GraveAccent, SDL_SCANCODE_GRAVE},
                                     {Key::Www, SDL_SCANCODE_WWW},
                                     {Key::Escape, SDL_SCANCODE_ESCAPE},
                                     {Key::Enter, SDL_SCANCODE_RETURN},
                                     {Key::Tab, SDL_SCANCODE_TAB},
                                     {Key::Backspace, SDL_SCANCODE_BACKSPACE},
                                     {Key::Insert, SDL_SCANCODE_INSERT},
                                     {Key::Delete, SDL_SCANCODE_DELETE},
                                     {Key::Right, SDL_SCANCODE_RIGHT},
                                     {Key::Left, SDL_SCANCODE_LEFT},
                                     {Key::Down, SDL_SCANCODE_DOWN},
                                     {Key::Up, SDL_SCANCODE_UP},
                                     {Key::PageUp, SDL_SCANCODE_PAGEUP},
                                     {Key::PageDown, SDL_SCANCODE_PAGEDOWN},
                                     {Key::Home, SDL_SCANCODE_HOME},
                                     {Key::End, SDL_SCANCODE_END},
                                     {Key::CapsLock, SDL_SCANCODE_CAPSLOCK},
                                     {Key::ScrollLock, SDL_SCANCODE_SCROLLLOCK},
                                     {Key::NumLock, SDL_SCANCODE_NUMLOCKCLEAR},
                                     {Key::PrintScreen, SDL_SCANCODE_PRINTSCREEN},
                                     {Key::Pause, SDL_SCANCODE_PAUSE},
                                     {Key::F1,

                                      SDL_SCANCODE_F1},
                                     {Key::F2, SDL_SCANCODE_F2},
                                     {Key::F3, SDL_SCANCODE_F3},
                                     {Key::F4, SDL_SCANCODE_F4},
                                     {Key::F5, SDL_SCANCODE_F5},
                                     {Key::F6, SDL_SCANCODE_F6},
                                     {Key::F7, SDL_SCANCODE_F7},
                                     {Key::F8, SDL_SCANCODE_F8},
                                     {Key::F9, SDL_SCANCODE_F9},
                                     {Key::F10, SDL_SCANCODE_F10},
                                     {Key::F11, SDL_SCANCODE_F11},
                                     {Key::F12, SDL_SCANCODE_F12},
                                     {Key::F13, SDL_SCANCODE_F13},
                                     {Key::F14, SDL_SCANCODE_F14},
                                     {Key::F15, SDL_SCANCODE_F15},
                                     {Key::F16, SDL_SCANCODE_F16},
                                     {Key::F17, SDL_SCANCODE_F17},
                                     {Key::F18, SDL_SCANCODE_F18},
                                     {Key::F19, SDL_SCANCODE_F19},
                                     {Key::F20, SDL_SCANCODE_F20},
                                     {Key::F21, SDL_SCANCODE_F21},
                                     {Key::F22, SDL_SCANCODE_F22},
                                     {Key::F23, SDL_SCANCODE_F23},
                                     {Key::F24, SDL_SCANCODE_F24},
                                     {Key::Kp0, SDL_SCANCODE_KP_0},
                                     {Key::Kp1, SDL_SCANCODE_KP_1},
                                     {Key::Kp2, SDL_SCANCODE_KP_2},
                                     {Key::Kp3, SDL_SCANCODE_KP_3},
                                     {Key::Kp4, SDL_SCANCODE_KP_4},
                                     {Key::Kp5, SDL_SCANCODE_KP_5},
                                     {Key::Kp6, SDL_SCANCODE_KP_6},
                                     {Key::Kp7, SDL_SCANCODE_KP_7},
                                     {Key::Kp8, SDL_SCANCODE_KP_8},
                                     {Key::Kp9, SDL_SCANCODE_KP_9},
                                     {Key::KpDecimal, SDL_SCANCODE_KP_DECIMAL},
                                     {Key::KpDivide, SDL_SCANCODE_KP_DIVIDE},
                                     {Key::KpMultiply, SDL_SCANCODE_KP_MULTIPLY},
                                     {Key::KpSubtract, SDL_SCANCODE_KP_MINUS},
                                     {Key::KpAdd, SDL_SCANCODE_KP_PLUS},
                                     {Key::KpEnter, SDL_SCANCODE_KP_ENTER},
                                     {Key::KpEqual, SDL_SCANCODE_KP_EQUALS},
                                     {Key::LeftShift, SDL_SCANCODE_LSHIFT},
                                     {Key::LeftControl, SDL_SCANCODE_LCTRL},
                                     {Key::LeftAlt, SDL_SCANCODE_LALT},
                                     {Key::LeftSuper, SDL_SCANCODE_LGUI},
                                     {Key::RightShift, SDL_SCANCODE_RSHIFT},
                                     {Key::RightControl, SDL_SCANCODE_RCTRL},
                                     {Key::RightAlt, SDL_SCANCODE_RALT},
                                     {Key::RightSuper, SDL_SCANCODE_RGUI},
                                     {Key::Menu, SDL_SCANCODE_MENU},
                                     {Key::MouseLeft, SDL_BUTTON_LEFT},
                                     {Key::MouseRight, SDL_BUTTON_RIGHT},
                                     {Key::MouseMiddle, SDL_BUTTON_MIDDLE}};

    static Map<int, Key> reversed_keyboard;

    static struct ReverseKeyboardGenerator {
        ReverseKeyboardGenerator()
        {
            for (auto& keyboard_pair : keyboard) reversed_keyboard[keyboard_pair.second] = keyboard_pair.first;
        }
    } rkb_gen;


    static Map<Key, String> key_names = {{Key::Unknown, "Unknown"},
                                         {Key::Space, "Space"},
                                         {Key::Apostrophe, "Apostrophe"},
                                         {Key::Comma, "Comma"},
                                         {Key::Minus, "Minus"},
                                         {Key::Period, "Period"},
                                         {Key::Slash, "Slash"},
                                         {Key::Num0, "0"},
                                         {Key::Num1, "1"},
                                         {Key::Num2, "2"},
                                         {Key::Num3, "3"},
                                         {Key::Num4, "4"},
                                         {Key::Num5, "5"},
                                         {Key::Num6, "6"},
                                         {Key::Num7, "7"},
                                         {Key::Num8, "8"},
                                         {Key::Num9, "9"},
                                         {Key::Semicolon, "Semicolon"},
                                         {Key::Equal, "Equal"},
                                         {Key::A, "A"},
                                         {Key::B, "B"},
                                         {Key::C, "C"},
                                         {Key::D, "D"},
                                         {Key::E, "E"},
                                         {Key::F, "F"},
                                         {Key::G, "G"},
                                         {Key::H, "H"},
                                         {Key::I, "I"},
                                         {Key::J, "J"},
                                         {Key::K, "K"},
                                         {Key::L, "L"},
                                         {Key::M, "M"},
                                         {Key::N, "N"},
                                         {Key::O, "O"},
                                         {Key::P, "P"},
                                         {Key::Q, "Q"},
                                         {Key::R, "R"},
                                         {Key::S, "S"},
                                         {Key::T, "T"},
                                         {Key::U, "U"},
                                         {Key::V, "V"},
                                         {Key::W, "W"},
                                         {Key::X, "X"},
                                         {Key::Y, "Y"},
                                         {Key::Z, "Z"},
                                         {Key::LeftBracket, "LeftBracket"},
                                         {Key::Backslash, "Backslash"},
                                         {Key::RightBracket, "RightBracket"},
                                         {Key::GraveAccent, "GraveAccent"},
                                         {Key::Www, "WWW"},
                                         {Key::Escape, "Escape"},
                                         {Key::Enter, "Enter"},
                                         {Key::Tab, "Tab"},
                                         {Key::Backspace, "Backspace"},
                                         {Key::Insert, "Insert"},
                                         {Key::Delete, "Delete"},
                                         {Key::Right, "Right"},
                                         {Key::Left, "Left"},
                                         {Key::Down, "Down"},
                                         {Key::Up, "Up"},
                                         {Key::PageUp, "PageUp"},
                                         {Key::PageDown, "PageDown"},
                                         {Key::Home, "Home"},
                                         {Key::End, "End"},
                                         {Key::CapsLock, "CapsLock"},
                                         {Key::ScrollLock, "ScrollLock"},
                                         {Key::NumLock, "NumLock"},
                                         {Key::PrintScreen, "PrintScreen"},
                                         {Key::Pause, "Pause"},
                                         {Key::F1, "F1"},
                                         {Key::F2, "F2"},
                                         {Key::F3, "F3"},
                                         {Key::F4, "F4"},
                                         {Key::F5, "F5"},
                                         {Key::F6, "F6"},
                                         {Key::F7, "F7"},
                                         {Key::F8, "F8"},
                                         {Key::F9, "F9"},
                                         {Key::F10, "F10"},
                                         {Key::F11, "F11"},
                                         {Key::F12, "F12"},
                                         {Key::F13, "F13"},
                                         {Key::F14, "F14"},
                                         {Key::F15, "F15"},
                                         {Key::F16, "F16"},
                                         {Key::F17, "F17"},
                                         {Key::F18, "F18"},
                                         {Key::F19, "F19"},
                                         {Key::F20, "F20"},
                                         {Key::F21, "F21"},
                                         {Key::F22, "F22"},
                                         {Key::F23, "F23"},
                                         {Key::F24, "F24"},
                                         {Key::Kp0, "Kp0"},
                                         {Key::Kp1, "Kp1"},
                                         {Key::Kp2, "Kp2"},
                                         {Key::Kp3, "Kp3"},
                                         {Key::Kp4, "Kp4"},
                                         {Key::Kp5, "Kp5"},
                                         {Key::Kp6, "Kp6"},
                                         {Key::Kp7, "Kp7"},
                                         {Key::Kp8, "Kp8"},
                                         {Key::Kp9, "Kp9"},
                                         {Key::KpDecimal, "KpDecimal"},
                                         {Key::KpDivide, "KpDivide"},
                                         {Key::KpMultiply, "KpMultiply"},
                                         {Key::KpSubtract, "KpSubtract"},
                                         {Key::KpAdd, "KpAdd"},
                                         {Key::KpEnter, "KpEnter"},
                                         {Key::KpEqual, "KpEqual"},
                                         {Key::LeftShift, "LeftShift"},
                                         {Key::LeftControl, "LeftControl"},
                                         {Key::LeftAlt, "LeftAlt"},
                                         {Key::LeftSuper, "LeftSuper"},
                                         {Key::RightShift, "RightShift"},
                                         {Key::RightControl, "RightControl"},
                                         {Key::RightAlt, "RightAlt"},
                                         {Key::RightSuper, "RightSuper"},
                                         {Key::Menu, "Menu"},
                                         {Key::MouseLeft, "MouseLeft"},
                                         {Key::MouseRight, "MouseRight"},
                                         {Key::MouseMiddle, "MouseMiddle"}};


    ENGINE_EXPORT int to_SDL_scancode(const Key& key)
    {
        return keyboard.at(key);
    }

    ENGINE_EXPORT wchar_t to_character(const Key& key)
    {
        return SDL_GetKeyFromScancode((SDL_Scancode) to_SDL_scancode(key));
    }

    ENGINE_EXPORT Key to_key(int value)
    {
        return reversed_keyboard.at(value);
    }

    ENGINE_EXPORT const String& get_key_name(const Key& key)
    {
        return key_names.at(key);
    }

    ENGINE_EXPORT std::ostream& operator<<(std::ostream& stream, const KeyStatus& status)
    {
        static Map<KeyStatus, const char*> names = {{KeyStatus::JustPressed, "JustPressed"},
                                                    {KeyStatus::Released, "Released"},
                                                    {KeyStatus::JustPressed, "JustPressed"},
                                                    {KeyStatus::Pressed, "Pressed"},
                                                    {KeyStatus::Repeat, "Repeat"}};
        return stream << names.at(status);
    }

    ENGINE_EXPORT unsigned int key_count()
    {
        return 130;
    }
}// namespace Engine
