#pragma once

// Do not edit this file is generated from slang-cpp-extractor tool



 /* !!!!!!!!!!!!!!!!!!!!!!!!!!!!! CHILDREN !!!!!!!!!!!!!!!!!!!!!!!!!!!! */ 

#define SLANG_CHILDREN_Value_DeclCheckStateExt(x, param)

#define SLANG_CHILDREN_Value_QualType(x, param)

#define SLANG_CHILDREN_Value_TypeExp(x, param)

#define SLANG_CHILDREN_Value_LookupResultItem(x, param)

#define SLANG_CHILDREN_Value_RequirementWitness(x, param)

#define SLANG_CHILDREN_Value_SpecializationArg(x, param) \
    SLANG_ALL_Value_ExpandedSpecializationArg(x, param)

#define SLANG_CHILDREN_Value_ExpandedSpecializationArg(x, param)

#define SLANG_CHILDREN_Value_SPIRVAsmOperand(x, param)

#define SLANG_CHILDREN_Value_SPIRVAsmInst(x, param)



 /* !!!!!!!!!!!!!!!!!!!!!!!!!!!!! ALL !!!!!!!!!!!!!!!!!!!!!!!!!!!! */

#define SLANG_ALL_Value_DeclCheckStateExt(x, param) \
    SLANG_Value_DeclCheckStateExt(x, param)

#define SLANG_ALL_Value_QualType(x, param) \
    SLANG_Value_QualType(x, param)

#define SLANG_ALL_Value_TypeExp(x, param) \
    SLANG_Value_TypeExp(x, param)

#define SLANG_ALL_Value_LookupResultItem(x, param) \
    SLANG_Value_LookupResultItem(x, param)

#define SLANG_ALL_Value_RequirementWitness(x, param) \
    SLANG_Value_RequirementWitness(x, param)

#define SLANG_ALL_Value_SpecializationArg(x, param) \
    SLANG_Value_SpecializationArg(x, param) \
    SLANG_CHILDREN_Value_SpecializationArg(x, param)

#define SLANG_ALL_Value_ExpandedSpecializationArg(x, param) \
    SLANG_Value_ExpandedSpecializationArg(x, param)

#define SLANG_ALL_Value_SPIRVAsmOperand(x, param) \
    SLANG_Value_SPIRVAsmOperand(x, param)

#define SLANG_ALL_Value_SPIRVAsmInst(x, param) \
    SLANG_Value_SPIRVAsmInst(x, param)



 /* !!!!!!!!!!!!!!!!!!!!!!!!!!!!! FIELDS !!!!!!!!!!!!!!!!!!!!!!!!!!!! */

#define SLANG_FIELDS_Value_DeclCheckStateExt(_x_, _param_)\
    _x_(m_raw, (RawType), _param_)

#define SLANG_FIELDS_Value_QualType(_x_, _param_)\
    _x_(type, (Type*), _param_)\
    _x_(isLeftValue, (bool), _param_)

#define SLANG_FIELDS_Value_TypeExp(_x_, _param_)\
    _x_(exp, (Expr*), _param_)\
    _x_(type, (Type*), _param_)

#define SLANG_FIELDS_Value_LookupResultItem(_x_, _param_)\
    _x_(declRef, (DeclRef<Decl>), _param_)\
    _x_(breadcrumbs, (RefPtr<LookupResultItem_Breadcrumb>), _param_)

#define SLANG_FIELDS_Value_RequirementWitness(_x_, _param_)\
    _x_(m_flavor, (Flavor), _param_)\
    _x_(m_declRef, (DeclRef<Decl>), _param_)\
    _x_(m_obj, (RefPtr<RefObject>), _param_)\
    _x_(m_val, (Val*), _param_)

#define SLANG_FIELDS_Value_SpecializationArg(_x_, _param_)\
    _x_(val, (Val*), _param_)

#define SLANG_FIELDS_Value_ExpandedSpecializationArg(_x_, _param_)\
    _x_(witness, (Val*), _param_)

#define SLANG_FIELDS_Value_SPIRVAsmOperand(_x_, _param_)\
    _x_(flavor, (Flavor), _param_)\
    _x_(token, (Token), _param_)\
    _x_(expr, (Expr*), _param_)\
    _x_(bitwiseOrWith, (List<SPIRVAsmOperand>), _param_)\
    _x_(knownValue, (SpvWord), _param_)\
    _x_(wrapInId, (bool), _param_)\
    _x_(type, (TypeExp), _param_)

#define SLANG_FIELDS_Value_SPIRVAsmInst(_x_, _param_)\
    _x_(opcode, (SPIRVAsmOperand), _param_)\
    _x_(operands, (List<SPIRVAsmOperand>), _param_)

