#pragma once

// Do not edit this file is generated from slang-cpp-extractor tool



 /* !!!!!!!!!!!!!!!!!!!!!!!!!!!!! CHILDREN !!!!!!!!!!!!!!!!!!!!!!!!!!!! */ 

#define SLANG_CHILDREN_RefObject_SerialRefObject(x, param) \
    SLANG_ALL_RefObject_LookupResultItem_Breadcrumb(x, param)\
    SLANG_ALL_RefObject_WitnessTable(x, param)\
    SLANG_ALL_RefObject_DeclAssociation(x, param)\
    SLANG_ALL_RefObject_DeclAssociationList(x, param)\
    SLANG_ALL_RefObject_MarkupEntry(x, param)

#define SLANG_CHILDREN_RefObject_LookupResultItem_Breadcrumb(x, param)

#define SLANG_CHILDREN_RefObject_WitnessTable(x, param)

#define SLANG_CHILDREN_RefObject_DeclAssociation(x, param)

#define SLANG_CHILDREN_RefObject_DeclAssociationList(x, param)

#define SLANG_CHILDREN_RefObject_MarkupEntry(x, param)



 /* !!!!!!!!!!!!!!!!!!!!!!!!!!!!! ALL !!!!!!!!!!!!!!!!!!!!!!!!!!!! */

#define SLANG_ALL_RefObject_SerialRefObject(x, param) \
    SLANG_RefObject_SerialRefObject(x, param) \
    SLANG_CHILDREN_RefObject_SerialRefObject(x, param)

#define SLANG_ALL_RefObject_LookupResultItem_Breadcrumb(x, param) \
    SLANG_RefObject_LookupResultItem_Breadcrumb(x, param)

#define SLANG_ALL_RefObject_WitnessTable(x, param) \
    SLANG_RefObject_WitnessTable(x, param)

#define SLANG_ALL_RefObject_DeclAssociation(x, param) \
    SLANG_RefObject_DeclAssociation(x, param)

#define SLANG_ALL_RefObject_DeclAssociationList(x, param) \
    SLANG_RefObject_DeclAssociationList(x, param)

#define SLANG_ALL_RefObject_MarkupEntry(x, param) \
    SLANG_RefObject_MarkupEntry(x, param)



 /* !!!!!!!!!!!!!!!!!!!!!!!!!!!!! FIELDS !!!!!!!!!!!!!!!!!!!!!!!!!!!! */

#define SLANG_FIELDS_RefObject_SerialRefObject(_x_, _param_)

#define SLANG_FIELDS_RefObject_LookupResultItem_Breadcrumb(_x_, _param_)\
    _x_(kind, (Kind), _param_)\
    _x_(thisParameterMode, (ThisParameterMode), _param_)\
    _x_(declRef, (DeclRef<Decl>), _param_)\
    _x_(val, (Val*), _param_)\
    _x_(next, (RefPtr<LookupResultItem_Breadcrumb>), _param_)

#define SLANG_FIELDS_RefObject_WitnessTable(_x_, _param_)\
    _x_(baseType, (Type*), _param_)\
    _x_(witnessedType, (Type*), _param_)\
    _x_(isExtern, (bool), _param_)\
    _x_(m_requirements, (List<KeyValuePair<Decl*,RequirementWitness>>), _param_)

#define SLANG_FIELDS_RefObject_DeclAssociation(_x_, _param_)\
    _x_(kind, (DeclAssociationKind), _param_)\
    _x_(decl, (Decl*), _param_)

#define SLANG_FIELDS_RefObject_DeclAssociationList(_x_, _param_)\
    _x_(associations, (List<RefPtr<DeclAssociation>>), _param_)

#define SLANG_FIELDS_RefObject_MarkupEntry(_x_, _param_)\
    _x_(m_node, (NodeBase*), _param_)\
    _x_(m_markup, (String), _param_)\
    _x_(m_visibility, (MarkupVisibility), _param_)

