#pragma once

// Do not edit this file is generated from slang-cpp-extractor tool

namespace Slang {

enum class RefObjectType
{
SerialRefObject = 0,
    LookupResultItem_Breadcrumb = 1,
    WitnessTable = 2,
    DeclAssociation = 3,
    DeclAssociationList = 4,
    MarkupEntry = 5,
    CountOf
};

// Predeclare

class SerialRefObject;
class LookupResultItem_Breadcrumb;
struct WitnessTable;
struct DeclAssociation;
struct DeclAssociationList;
struct MarkupEntry;
// Type macros

// Order is (NAME, SUPER, ORIGIN, LAST, MARKER, TYPE, param) 
// NAME - is the class name
// SUPER - is the super class name (or NO_SUPER)
// ORIGIN - where the definition was found
// LAST - is the class name for the last in the range (or NO_LAST)
// MARKER - is the text inbetween in the prefix/postix (like ABSTRACT). If no inbetween text is is 'NONE'
// TYPE - Can be BASE, INNER or LEAF for the overall base class, an INNER class, or a LEAF class
// param is a user defined parameter that can be parsed to the invoked x macro

#define SLANG_RefObject_SerialRefObject(x, param)     x(SerialRefObject, NO_SUPER, AST_SUPPORT_TYPES, MarkupEntry, NONE, BASE, param)
#define SLANG_RefObject_LookupResultItem_Breadcrumb(x, param)     x(LookupResultItem_Breadcrumb, SerialRefObject, AST_SUPPORT_TYPES, LookupResultItem_Breadcrumb, OBJ, LEAF, param)
#define SLANG_RefObject_WitnessTable(x, param)     x(WitnessTable, SerialRefObject, AST_SUPPORT_TYPES, WitnessTable, OBJ, LEAF, param)
#define SLANG_RefObject_DeclAssociation(x, param)     x(DeclAssociation, SerialRefObject, AST_SUPPORT_TYPES, DeclAssociation, OBJ, LEAF, param)
#define SLANG_RefObject_DeclAssociationList(x, param)     x(DeclAssociationList, SerialRefObject, AST_SUPPORT_TYPES, DeclAssociationList, OBJ, LEAF, param)
#define SLANG_RefObject_MarkupEntry(x, param)     x(MarkupEntry, SerialRefObject, AST_SUPPORT_TYPES, MarkupEntry, OBJ, LEAF, param)
} // namespace Slang
