# Build type
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON  CACHE BOOL "" FORCE)

# Keep what we need
set(SDL_VIDEO ON CACHE BOOL "" FORCE)

# Disable unused SDL subsystems
set(SDL_AUDIO        OFF CACHE BOOL "" FORCE)
set(SDL_GPU          ON CACHE BOOL "" FORCE)
set(SDL_RENDER       ON CACHE BOOL "" FORCE)
set(SDL_CAMERA       OFF CACHE BOOL "" FORCE)
set(SDL_JOYSTICK     OFF CACHE BOOL "" FORCE)
set(SDL_HAPTIC       OFF CACHE BOOL "" FORCE)
set(SDL_HIDAPI       OFF CACHE BOOL "" FORCE)
set(SDL_POWER        OFF CACHE BOOL "" FORCE)
set(SDL_SENSOR       OFF CACHE BOOL "" FORCE)
set(SDL_DIALOG       OFF CACHE BOOL "" FORCE)
set(SDL_TRAY         OFF CACHE BOOL "" FORCE)
set(SDL_NOTIFICATION OFF CACHE BOOL "" FORCE)
set(SDL_X11_XSCRNSAVER OFF CACHE BOOL "" FORCE)

# Don't build SDL extras
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_TESTS        OFF CACHE BOOL "" FORCE)
set(SDL_EXAMPLES     OFF CACHE BOOL "" FORCE)
set(SDL_INSTALL      OFF CACHE BOOL "" FORCE)

add_subdirectory(libs/SDL3-3.4.16)


file(GLOB_RECURSE TRINEX_PLATFORM_SDL_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
target_include_directories(TrinexEngine PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_sources(TrinexEngine PRIVATE ${TRINEX_PLATFORM_SDL_SOURCES})
target_link_libraries(TrinexEngine PRIVATE SDL3::SDL3-static)
